### ISSUE TITLE
Move to rabbitmq-provided Debian packages

### ISSUE THREAD

**Issue by yosifkit** [docker-library/rabbitmq#129]
:tada: Rabbitmq upstream has an apt repo: `http://www.rabbitmq.com/debian/`.

> RabbitMQ hosts our own apt repository. We also have an alternative repository on Package Cloud.
> \- https://www.rabbitmq.com/install-debian.html

Not sure if it varies from the erlang-solutions repo. Definitely worth testing it.

**Comment by tianon** [comment]
That's the one we use: https://github.com/docker-library/rabbitmq/blob/c766dd4dad64dd1c5550febff7e19ab763b7c5a4/Dockerfile#L47-L50

(We only use Erlang Solutions to pull in Erlang itself, since RabbitMQ's repo doesn't include Erlang packages and we want more recent versions than Debian provides, IIRC)

**Comment by yosifkit** [comment]
:disappointed: I'm just crazy.
