### ISSUE TITLE
How to configure memory settings?

### ISSUE THREAD

**Issue by betrcode** [docker-library/rabbitmq#132]
It seems `docker-entrypoint.sh` creates/overwrites the configuration file for rabbitmq.

Maybe I have missed something obvious in the documentation, but how do I get in custom configuration into the config file? Example, I'd like to be able to set `vm_memory_high_watermark_paging_ratio` as described in https://www.rabbitmq.com/memory.html

Help is much appreciated!

Update: This seems to be related to #76 and #120

**Comment by tianon** [comment]
Currently the only way to do so is by choosing to either fork our entrypoint script or to ignore our environment variables and create the entire configuration file yourself (which is what I'd recommend).

At some point (hoepfully soon), upstream is going to replace their Erlang-based configuration file with an INI-ish syntax, which will allow us to be more forgiving of existing user-supplied content (by appending/modifying instead of replacing completely). :+1:

**Comment by betrcode** [comment]
Thanks @tianon 
I think the simplest way to go is to set the `RABBITMQ_CONFIG_FILE` environment variable when starting the docker container, and refer to a custom configuration file which we can provision in a mapped docker volume.

**Comment by ash9002** [comment]
@betrcode @tianon 

How is this done?

I've tried 

`docker service create --name rmq --network rnet -e RABBITMQ_ERLANG_COOKIE='arsenal' --mount type=bind,source=/root/mounted/,destination=/root -e RABBITMQ_CONFIG_FILE=/root/rabbitmq.config rabbitmq`

But when I look at the rabbitmq.config in the container it's still the default one containing the following:
`[ { rabbit, [ { loopback_users, [ ] } ] } ].`
