### ISSUE TITLE
ACCESS_REFUSED when changing default credentials 

### ISSUE THREAD

**Issue by kdekooter** [docker-library/rabbitmq#139]
I changed the default user by setting the `RABBITMQ_DEFAULT_USER` and `RABBITMQ_DEFAULT_PASS` environmental variables. However when I now try to connect a (Java) client I get the following exception:

```ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.```

I suppose I need to somehow configure this user inside RabbitMQ (as outlined here: http://stackoverflow.com/questions/26811924/spring-amqp-rabbitmq-3-3-5-access-refused-login-was-refused-using-authentica/26820152). Can this be configured in the docker startup parameters?

**Comment by michaelklishin** [comment]
@kdekooter that's too little information to suggest anything. See server logs for more details. 

Default user [can only connect from localhost](http://www.rabbitmq.com/access-control.html) due to security considerations.

`RABBITMQ_DEFAULT_USER` simply [overrides the credentials in `rabbitmq.config`](https://github.com/docker-library/rabbitmq/commit/97e1f49042fd2cf6153ddf7c17112f391558fd35) but does not lift the restriction. The right thing to do is to delete the default user and create a new one tagged as `administrator`. I am not convinced this is something this image should be concerned with.

**Comment by kdekooter** [comment]
Fair enough (and thanks for the swift response). Should I mount a customized `rabbitmq.config` into the image?

**Comment by kdekooter** [comment]
I am very sorry @michaelklishin I submitted this issue too fast. Turned out I misconfigured my client :-(. Setting the default user does work as expected.

Can you please delete this issue?

**Comment by michaelklishin** [comment]
@kdekooter GitHub issues cannot be deleted even by repository owners (and I'm not one to begin with), sorry. You can blank the description and set the title to "N/A" or something if you would rather not have this public.
