### ISSUE TITLE
Please add docker-compose environment variable CLUSTER_WITH to take a node name as input

### ISSUE THREAD

**Issue by mahendran-ayyasamy** [docker-library/rabbitmq#164]
CLUSTER_WITH should take a host name and upon finding a hostname with that name, it should cluster with that node

**Comment by Gsantomaggio** [comment]
You should consider using [rabbitmq-autocluster](https://github.com/rabbitmq/rabbitmq-autocluster) plugin to create the clusters, instead `CLUSTER_WITH` variable

`CLUSTER_WITH` needs a node to bind the other nodes, with rabbitmq-autocluster you can use different backends and bind the nodes dynamically. So you don't need a "master cluster node".

Currently, it supports:

- AWS EC2 tags
- AWS Autoscaling Groups
- Kubernetes
- DNS A records
- Consul
- etcd

There are a couple of examples to use it on Kubernetes:

- [Deploy on K8s](https://github.com/rabbitmq/rabbitmq-autocluster/tree/master/examples/k8s_minikube)

- [Deploy on K8s using StatefulSet Controller](https://github.com/rabbitmq/rabbitmq-autocluster/tree/stable/examples/k8s_statefulsets) 

The full documentation is available [here](https://github.com/rabbitmq/rabbitmq-autocluster#rabbitmq-autocluster) 

The current  version is [`0.8.0`](https://github.com/rabbitmq/rabbitmq-autocluster/releases/tag/0.8.0)

**Comment by yosifkit** [comment]
Sorry for the long delay. We'd rather keep the scripts and config in the image as minimal as possible. See also https://github.com/docker-library/rabbitmq/pull/202#issuecomment-337414006 and linked issues.

Since the introduction of the 3.7 image, you can supply `/etc/rabbitmq/rabbitmq.conf` and the entrypoint will only add/sed supplied envs while leaving other lines in the file untouched (https://github.com/docker-library/rabbitmq/pull/197#issuecomment-350346234).
