### ISSUE TITLE
No logs are seen in /var/log/rabbitmq

### ISSUE THREAD

**Issue by w7089** [docker-library/rabbitmq#184]
Hi, i have set env variable 

`RABBITMQ_LOG_BASE=/var/log/rabbitmq`

during service deployment and its value is seen in the container.

But _/var/log/rabbitmq_ is empty.

While doing `docker logs -f container_id` does show the logs.
Where are the logs stored and how to see them?

**Comment by michaelklishin** [comment]
It would help if you clarified how exactly was the environment variable set. [Default directory locations](http://www.rabbitmq.com/relocate.html) are documented.

**Comment by w7089** [comment]
Hi, Michael.
Thanks.
It was set in service descriptor _yaml_

```  
      ...
      environment:              
        - RABBITMQ_LOG_BASE=/var/log/rabbitmq  
      ...
```

**Comment by yosifkit** [comment]
They are stored in Docker logs which can be configured to be sent to a logging service (for example, via gelf or syslog).  If you really need it to write to a file inside the container, then you need to also set `RABBITMQ_LOGS` and `RABBITMQ_SASL_LOGS` since we set them to std out in the Dockerfile:

https://github.com/docker-library/rabbitmq/blob/ba7ea670b5c084417d1f03cb07012314ba51c57a/3.6/debian/Dockerfile#L53-L55

**Comment by tianon** [comment]
Indeed, this is by design -- if you want the logs to go to files, you'll need to unset or override the provided `RABBITMQ_LOGS` and/or `RABBITMQ_SASL_LOGS` environment variables.
