### ISSUE TITLE
5672 can not access the user interface

### ISSUE THREAD

**Issue by xingxing9688** [docker-library/rabbitmq#233]

**Comment by tianon** [comment]
This issue does not have enough detail required for folks to reproduce your issue, let alone help diagnose the problem and suggest a fix.

I'd recommend putting together a simple and short set of commands/instructions which can reproduce the problem, and then posting it to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker) (any of which will give you a larger potential group of folks who are willing to help).

Since we cannot reproduce the problem and it appears to be an issue with usage and not the image, I'm going to close.  Thanks!
