### ISSUE TITLE
Facing the error while running the eshoponcontainer

### ISSUE THREAD

**Issue by RachanaNayak** [docker-library/rabbitmq#234]
![screenshot 59](https://user-images.githubusercontent.com/33618456/34975083-21206da2-fab6-11e7-89d6-eed6c76637c5.png)

We are facing this error while running the eshoponcontainer

**Comment by tianon** [comment]
I don't see any container logs here (only error messages from `docker-compose` failing to even start the container, so I can't see how this could be caused by the image, or to put that another way, what we could change in the image to fix it) -- this looks like an issue with your local configuration, your `docker-compose.yml`, or your local environment.  As such, I'm going to close since I don't see any image adjustments we can make here.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).  Thanks!
