### ISSUE TITLE
3.7.5-Alpine image contains CRITICAL vulnerability (CVE-2017-11164)

### ISSUE THREAD

**Issue by NiharPattanaik** [docker-library/rabbitmq#261]
Hi,

PCRE 8.41 library included in erlang-20.1.7-r2 has a Critical security vulnerability (CVE-2017-11164). The details can be found here.

https://nvd.nist.gov/vuln/detail/CVE-2017-11164

This critical vulnerability is restricting us to bundle RabbitMQ in our product. Could you please help me if there is any fix available for this issue.

Regards,
Nihar

**Comment by michaelklishin** [comment]
Use [a newer Erlang version](http://www.rabbitmq.com/which-erlang.html).

**Comment by tianon** [comment]
Ouch, we can't really control the Erlang version in Alpine unless we compile Erlang from source. :disappointed:

I suppose we need to play around with doing `FROM erlang` (https://hub.docker.com/_/erlang/) instead of `FROM alpine`.

As for the vulnerability reported on Docker Hub -- we can't really do anything about that, it comes from a package provided by Alpine, and that package in Alpine's repos will need to be updated for that CVE to become actionable.

**Comment by yosifkit** [comment]
This CVE would need to be reported in the Alpine Linux bug tracker, probably related to https://bugs.alpinelinux.org/issues/7700. I don't know which erlang package we install that contains the bundled PCRE lib, but here is the list:

https://github.com/docker-library/rabbitmq/blob/d7096266dfb047fce1eff89bd759e3ab55d779f3/3.7/alpine/Dockerfile#L9-L27

I am not sure about moving to `FROM erlang` since it is much larger than the current image:
```console
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
rabbitmq            3.7-alpine          3ef6d2255bf6        19 hours ago        46.7MB
erlang              20.3-alpine         038de6297278        3 weeks ago         75.5MB
```

**Comment by NiharPattanaik** [comment]
Hi Michael,

I have verified the latest erlang-20.3.6-1.el7.centos.x86_64.rpm, this also has the same vulnerability. Is there any plan from erlang to fix this.

Regards,
Nihar

**Comment by tianon** [comment]
Debian hasn't even fixed this particular CVE in their `pcre` package yet: https://security-tracker.debian.org/tracker/CVE-2017-11164 :confused: :disappointed: 

(So there's really nothing we can do here.)

**Comment by wglambert** [comment]
Going to close this as there isn't anything actionable for us, when upstream fixes it then the images will be updated to include the upstream changes
