### ISSUE TITLE
Disable TLS 1.0

### ISSUE THREAD

**Issue by anhvutnu** [docker-library/rabbitmq#287]
Hello,
Is there away to set SSL_VERSION for rabbitmq through env variables?

**Comment by wglambert** [comment]
https://www.rabbitmq.com/ssl.html#tls-versions

Looks like it's only through the config file

**Comment by anhvutnu** [comment]
@wglambert Thanks! Do you by any chance know if docker-entrypoint.sh would overwrite the rabbitmq.conf file if there is one ?

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/rabbitmq#additional-configuration
It doesn't, so mounting a file to `/etc/rabbitmq/rabbitmq.conf` is the preferred way to modify the file.

Alternatively, it is possible to use the `RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS` environment variable, whose syntax is described [in section 7.8 ("Configuring an Application") of the Erlang OTP Design Principles User's Guide](http://erlang.org/doc/design_principles/applications.html#id81887) (the appropriate value for `-ApplName` is `-rabbit`), but this method is much harder to get right than the configuration file format suggested above.

I'm going to close since the issue is resolved, in the future if you have questions about the images you should ask [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repositories are for issues with the image and not necessarily for questions of usability
