### ISSUE TITLE
Define an Exchange

### ISSUE THREAD

**Issue by ccruz2886** [docker-library/rabbitmq#303]
I would like to know if there's a way to create an exchange on the docker-compose as we create the virtual host by using `RABBITMQ_DEFAULT_VHOST=dev`. Maybe something like 
- `RABBITMQ_DEFAULT_EXCHANGE=Foo`
- `RABBITMQ_DEFAULT_EXCHANGE_TYPE=topic`
- `RABBITMQ_DEFAULT_EXCHANGE_DURABILITY=Foo` and so on.

Suggestions! 

Thanks in advance

**Comment by wglambert** [comment]
Perhaps you could create a script to invoke rabbitmqctl commands to create the exchanges http://www.rabbitmq.com/amqp-0-9-1-quickref.html#class.exchange

There's also https://stackoverflow.com/a/48821593 and https://devops.datenkollektiv.de/creating-a-custom-rabbitmq-container-with-preconfigured-queues.html

**Comment by tianon** [comment]
Since this is something that can be placed in a `definitions.json` file (https://www.rabbitmq.com/management.html#load-definitions), that's probably your simplest / most declarative solution here.

(Closing, since adding additional behavior for this isn't something we plan to do in this image, especially given that a definitions file appears to be the appropriate way to do so.)
