### ISSUE TITLE
Cant start image on Debian with grsec Kernel

### ISSUE THREAD

**Issue by opHASnoNAME** [docker-library/rabbitmq#313]
Latest image is not starting on Debian-Grsec Kernel. Version 3.7.8 works fine.

Docker logs:

`/bin/sh: bad interpreter: Permission denied`

Kernel Log on Docker-Host

```
[1801325.734604] grsec: [rabbit] denied untrusted exec (due to not being in trusted group and file in non-root-owned directory) 
of /opt/rabbitmq/sbin/rabbitmq-plugins by /opt/rabbitmq/sbin/rabbitmq-plugins[docker-entrypoi:23395] 
uid/euid:100/100 gid/egid:101/101, parent /usr/local/bin/docker-entrypoint.sh[docker-entrypoi:23217] 
uid/euid:100/100 gid/egid:101/101
```
Any suggestions?

**Comment by michaelklishin** [comment]
Add all RabbitMQ executables to a trusted group?

**Comment by tianon** [comment]
Trying to run arbitrary container images on a grsec or hardened kernel is pretty ambitious in general, IMO.

**Comment by wglambert** [comment]
You could also try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability

Closing since this is an issue with the environment
