### ISSUE TITLE
Dockerfile use USER

### ISSUE THREAD

**Issue by dadez** [docker-library/rabbitmq#320]
Can you explain why you do not use the "`USER rabbitmq`" before setting the `ENTRYPOINT` at the end of the Dockerfile ?
If we do that, we can avoid to use `su-exec` in the docker-entrypoint.sh file which in my case causes problems in kubernetes with Pod Security Policies

**Comment by tianon** [comment]
Permissions are the primary reason -- for a non-trivial number of users, getting permissions right is very difficult, and so by default the image starts as `root` and steps down right afterwards so it can do the following:

https://github.com/docker-library/rabbitmq/blob/c9712e6f8d95ec11872c876cea2c20e8eacb52ed/docker-entrypoint.sh#L108

All that is couched in an `if` that checks whether we're running as `root` so that you can use `user:` or `--user` to override that and run directly as `rabbitmq` (or really, any arbitrary user) instead.
