### ISSUE TITLE
Setting environment variable RABBITMQ-DEFAULT_VHOST fails

### ISSUE THREAD

**Issue by tvld** [docker-library/rabbitmq#323]
This works fine, RabbitMQ starts after ``docker-compose up``:
```.yml
version: '3'

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "qrespi_01"
    restart: always
    environment:
        - RABBITMQ_DEFAULT_USER = myuser
        - RABBITMQ_DEFAULT_PASS = mypassword

    ports:
      - "15672:15672"
      - "15674:15674"
      - "5672:5672"
      - "1884:1883"
    labels:
      NAME: "qmesque"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.conf
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
```

But when I add to the environments,
```yml
       - RABBITMQ_DEFAULT_VHOST= my_vhost
```
I get errors in the docker log:
```
sed: cannot rename /etc/rabbitmq/sedp33hvn: Device or resource busy
sed: cannot rename /etc/rabbitmq/sedJyBKgN: Device or resource busy

```

**Comment by tvld** [comment]
Work around is to keep the configuration fully in the  ``rabbitmq-isolated.conf`` file:
```yml
# allow from non localhost
loopback_users = none

# *** VARIABLES
default_user = my_user
default_pass = my_password
default_vhost = my_vhost
```

**Comment by tianon** [comment]
```yaml
    environment:
        - RABBITMQ_DEFAULT_USER = myuser
        - RABBITMQ_DEFAULT_PASS = mypassword
```

This is likely not doing what you expect -- you want to remove the spaces around the `=` sign here, otherwise I think you're getting environment variables which end in a literal space character (which isn't POSIX compliant, but technically should work if you had something that could read/was reading them).

The reason your addition breaks is because it does not have the space before the `=`, so it's actually creating a known environment variable which then invokes our entrypoint script.

If you're supplying a configuration file already, I'd highly recommend putting these values directly in your file instead of trying to mix-and-match by both providing a file and providing environment variables (which are a signal to the image that you want us to modify the configuration file, which doesn't make a lot of sense when that configuration file is provided by you already).

**Comment by tvld** [comment]
Right, I noticed it was indeed ignoring the password and user as well, just did not break on it...
So, clear... I will use the config file for all... Makes more sense indeed :+1:
