### ISSUE TITLE
quorum queue writes continue with 1 node

### ISSUE THREAD

**Issue by tajdars** [docker-library/rabbitmq#334]
Quorum queue on 3 node cluster. Stop 2 out of 3 nodes after some message published. Continue publishing messages. Queue Consumers stops when minority node(s) available but no impact on publish. Looks like messages get buffered and released when Queue has quorum.

Shouldn't the publish stop as well  when queue has no quorum ?

**Comment by michaelklishin** [comment]
Please post your questions to the mailing list. Quorum queues is an unreleased feature still under development and this image does not possibly change how they operate.

The way unsuccessful publishes are communicated back to the client is not by "stopping publishes" but via [negative publisher confirms](https://www.rabbitmq.com/confirms.html) or returned messages (when they are unroutable and published with the mandatory flag, which is not relevant here).

**Comment by michaelklishin** [comment]
Also please provide a set of steps to reproduce in the mailing list thread. There's some buffering going on in channels but it won't make a major difference if queue majority isn't available for, say, a few minutes (obviously this depends on rates). In order to explain what is really going on we need a lot more information than a two sentence description. Thanks.
