### ISSUE TITLE
[RFC]  add wget on ubuntu image

### ISSUE THREAD

**Issue by Gsantomaggio** [docker-library/rabbitmq#370]
In the same way as Alpine,  it would be useful to have `wget` installed on the Ubuntu image.
In the helm chat is used for [`livenessProbe`](https://github.com/helm/charts/blob/master/stable/rabbitmq-ha/values.yaml#L449) and `readinessProbe`

The rabbitmq deploy with ubuntu using helm chart, does not work, by given the following error:

```
Readiness probe failed: /bin/sh: 1: wget: not found 
```
Thank you.

**Comment by yosifkit** [comment]
We don't specifically install it in Alpine; `wget` only exists because it is from the base Alpine image via the busybox package. In both versions we specifically purge anything not from the base image and not required to run rabbitmq (ie build dependencies):

https://github.com/docker-library/rabbitmq/blob/fb3a168bf8efaf644cc8dbfc10f12e74f050f02d/3.7/ubuntu/Dockerfile#L165-L176
https://github.com/docker-library/rabbitmq/blob/fb3a168bf8efaf644cc8dbfc10f12e74f050f02d/3.7/ubuntu/Dockerfile#L239

Even though possibly small, it is not necessary. I recommend making an image `FROM` this that adds any customization you need or using a different image for the liveness check, like [`buildpack-deps:18.04-curl`](https://github.com/docker-library/buildpack-deps/blob/b0fc01aa5e3aed6820d8fed6f3301e0542fbeb36/bionic/curl/Dockerfile)

**Comment by Gsantomaggio** [comment]
ok thank you
