### ISSUE TITLE
rabbitmq uid and gid can't be overridden

### ISSUE THREAD

**Issue by karimzmi** [docker-library/rabbitmq#380]
https://github.com/docker-library/rabbitmq/blob/3d8ea96e0a1a54c995eedbc325df34e163224365/3.8/ubuntu/Dockerfile#L186

rabbitmq uid and gid are currently hardcoded in the dockerfile and set to 999 which conflicts with certain linux distros system daemons (redhat). Since there is no consensus among linux distros on system ranges (anything > 99) for uids, the rabbitmq container should offer the ability to override it.

**Comment by yosifkit** [comment]
This is the default user for the image, but have you tried just setting the user and group via `--user` on `docker run` (or equivalent).  This should have been available since #125.  The only thing to note is that if you provide a volume to the container, you'll need to ensure that it already has appropriate permissions for your user.
