### ISSUE TITLE
Alpine image is missing /etc/ssl/certs

### ISSUE THREAD

**Issue by oyviaase** [docker-library/rabbitmq#420]
Using the rabbitmq:3.8.3-alpine image from docker hub are we unable to find the `/etc/ssl/certs` folder on it. This might break shoveling to another amqps enabled host as rabbitmq is unable to verify the CA used by the other servers certificate

**Comment by oyviaase** [comment]
Using this file `/etc/ssl/cert.pem` where we able to create shovels with peer-validation and amqps. So it might just be enough to change the symlink in the docker file

**Comment by wglambert** [comment]
Looks like the same issue as https://github.com/docker-library/haproxy/issues/117#issuecomment-645126712

**Comment by yosifkit** [comment]
Not quite docker-library/haproxy#117, since this is still Alpine 3.11. We do install and remove `ca-certificates`, but the `/etc/ssl/cert.pem` file isn't a broken symlink after removal. Ah, but the `/etc/ssl/certs` folder is deleted by apk :cry:.  DId a quick test and `alpine:3.12` doesn't have this problem, so I'll make a PR to update it.
