### ISSUE TITLE
Update Ubuntu base image to LTS 20.04

### ISSUE THREAD

**Issue by alaendle** [docker-library/rabbitmq#450]
I think that it might be time to use a newer base image - the new ubuntu LTS 20.04 was released in April an so it should be stable now (https://ubuntu.com/about/release-cycle).

Even if the LTS 18.04 would still be supported with security fixes until April 2023 I think it might be worth to take a step and use LTS 20.04 as a base for new rabbitmq docker images (this should be a simple replacement of "18.04" with "20.04" - at least from my simple test use-cases the updated images run without any problems).

The main reason I see for using the newer LTS version is that some basic dependencies got updates - e.g. GLIBC is v.2.27 on bionic, while it is v2.31 on LTS 20.04 (https://packages.ubuntu.com/de/source/bionic/glibc, https://packages.ubuntu.com/de/source/focal/glibc) - and this is a huge burden for some native libraries. 

So from my perspective the divergence from actual software development environments to a April 2018 base system just got big enough to cause first pains; even if there are workarounds, I believe it is time to update the ubuntu base image to the "new" LTS release. At the very least with the rabbitmq 3.9 series, but may I hope for 3.8.10/11?

**Comment by tianon** [comment]
The primary reason I can see why we *wouldn't* just upgrade in place on RabbitMQ 3.8 would be compatibility -- how likely is it that something breaks?

(See https://github.com/docker-library/postgres/issues/582 for a concrete example of this that I don't *think* applies here, but is a useful example to show the kind of subtle breakage this might extend to and we should be aware of.)

Also relevant (and proof positive that this is likely "fine" and shouldn't cause problems) is https://github.com/docker-library/rabbitmq/pull/297 where we already did a switch from Debian to Ubuntu without too much fanfare. :smile:

**Comment by michaelklishin** [comment]
RabbitMQ Debian package is tested on multiple Ubuntu and Debian distributions, from 16.04 through 20.04, Debian Buster, Debian Bullseye. Outside of Debian-specific changes such as service management tools or obscure security limitations
that may affect package installation, we have never seen any issues.

One major reason to keep up with reasonably recent Linux distribution releases is OpenSSL upgrades: TLSv1.3 and
newer ECC curve adoption is on the rise, and older OpenSSL versions soon enough won't provide what the users want.

In fact, RabbitMQ Debian package had to drop Debian Stretch support because it does not provide OpenSSL 1.1
and this is the minimum realistic requirement for security-minded Erlang and RabbitMQ users these days.

**Comment by tianon** [comment]
We build our own OpenSSL here, so that's not a problem for us, but it sounds like there's not a good reason _not_ to update. :smile: :+1:
