### ISSUE TITLE
empty logs, even with RABBITMQ_LOGS set

### ISSUE THREAD

**Issue by ggmartins** [docker-library/rabbitmq#451]
please, have a lock at https://stackoverflow.com/questions/64952005/pika-rabbitmq-docker-with-tls-gen-connection-reset-no-logs
I'm trying really hard to get rabbitmq docker container to work with a simple self-signed certificate from tls-gen. I'm clueless as to what is causing this tcp connection reset w/o no clear info.

Thanks,

G

**Comment by wglambert** [comment]
We don't have any environment variables for `RABBITMQ_LOGS` or `RABBITMQ_SASL_LOGS` https://github.com/docker-library/docs/tree/master/rabbitmq#environment-variables
And following this example https://www.rabbitmq.com/ssl.html#automated-certificate-generation-transcript I was able to get ssl working just fine https://github.com/docker-library/rabbitmq/issues/376#issuecomment-541807243

**Comment by wglambert** [comment]
Closing since this seems resolved

If you have further questions you could try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
