### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by AHLinJie** [docker-library/rabbitmq#481]
docker run -d --hostname rabbit-dev --name rabbit -p 5672:5672 -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password rabbitmq:3-management

docker: error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/e2/e2b066e3fc02361ea494d96b3b30f4e2bc65d692fdc75fe73b1e245976a6c5d7/data?verify=1619751675-wooOCjlAB9GAlwjzHDnNH0EdPsA%3D: Bad Gateway.
See 'docker run --help'.
➜  ~

**Comment by wglambert** [comment]
I'm not able to reproduce, seems like a network issue with your environment. I would recommend asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

```console
$ docker pull rabbitmq:3-management
3-management: Pulling from library/rabbitmq
01bf7da0a88c: Pull complete 
f3b4a5f15c7a: Pull complete 
57ffbe87baa1: Pull complete 
5ef3ef76b1b5: Pull complete 
82a3ce07c0eb: Pull complete 
1da219d9bd70: Pull complete 
95357072940c: Pull complete 
48402ec96e12: Pull complete 
58280fe81054: Pull complete 
dc3da835675b: Pull complete 
2489f5125a1a: Pull complete 
b7988b8d0d95: Pull complete 
64a64e8686f4: Pull complete 
Digest: sha256:c7e1e3c34f1a6a5c089723763f04dc4c483d12f2fabb2fe48faee6f3d3998c69
Status: Downloaded newer image for rabbitmq:3-management
docker.io/library/rabbitmq:3-management
```
