### ISSUE TITLE
Enable web_stomp plugin

### ISSUE THREAD

**Issue by techniq** [docker-library/rabbitmq#5]
Is it possible to enable the `web_stomp` plugin with this image?  It appears to enable to management plugin you must use a specific docker tag(s) (`#-management`).  It would be nice if you could pass an environment variable to declare which plugins you need.

On our current project we've resorted to copying the Dockerfile so we may run `rabbitmq-plugins enable rabbitmq_web_stomp`, which seems kind of overkill to enable a plugin.

**Comment by yosifkit** [comment]
Since we already have an entrypoint defined, it is not too far of a stretch to add an ENV var to enable plugins, but then you have a possibly long `docker run` command.  I am leaning toward thinking that having your own docker image with the plugins ready to go would be better than telling operations and your developers that they need to run it with a `-e RABBIT_PLUGINS='enable all the plugins that we need'`.

**Comment by vovimayhem** [comment]
@yosifkit I'm not that much into making a new Dockerfile (using a FROM command) when the added functionality is small - like enabling a plugin - or can be solved by mounting a volume - I like to stay as official as I can :).

I liked the way the official postgresql [docker entrypoint file](https://github.com/docker-library/postgres/blob/master/9.3/docker-entrypoint.sh) checks a mountable volume for any extra initialization scripts (see [line 49](https://github.com/docker-library/postgres/blob/master/9.3/docker-entrypoint.sh#L49)). I've used that for initialization scripts (Adding databases, changing encoding, etc)

Maybe we could do the same in this image? Add initialization scripts into a folder which would - among other things - add & enable plugins, create vhosts, queues, etc.

How do you feel about this? @yosifkit @tianon

**Comment by yosifkit** [comment]
We do the init scripts directory for the postgres images since the database cannot be initialized until container start.  Since these plugins can be enabled beforehand (like in a RUN line), I would be hesitant to add a similar script directory here.  I think @tianon may have similar thoughts.

**Comment by tianon** [comment]
My thoughts exactly :+1:

The "initdb" support was added specifically because the functionality
provided there can't be duplicated in a Dockerfile easily.  In this case,
enabling plugins in a Dockerfile is trivial (as seen in
https://github.com/docker-library/rabbitmq/blob/5d74f800696dd55614b8c8cdcc142533563f83a1/management/Dockerfile).
Combine that with automated builds (
https://docs.docker.com/docker-hub/builds/) and repository links (
https://docs.docker.com/docker-hub/builds/#repository-links) and it's
reasonably easy to have an up-to-date image built FROM this one with extra
plugins enabled (and have the "enablement" baked into the image instead of
happening at container run time).

**Comment by vovimayhem** [comment]
Got it!

**Comment by techniq** [comment]
Fair enough explanation for me.  Thanks

**Comment by cecchisandrone** [comment]
Thanks for the explanation guys!
