### ISSUE TITLE
Architectures missing for rabbitmq:3.9.11-alpine

### ISSUE THREAD

**Issue by xoxys** [docker-library/rabbitmq#533]
```
Step 1/23 : FROM rabbitmq:3.9.11-alpine@sha256:cca783c29f00fd31bec1da964cb3c9cc8fc32e3388f62bc85257552ce5c8c796
docker.io/library/rabbitmq:3.9.11-alpine@sha256:cca783c29f00fd31bec1da964cb3c9cc8fc32e3388f62bc85257552ce5c8c796: Pulling from library/rabbitmq
docker.io/library/rabbitmq:3.9.11-alpine@sha256:cca783c29f00fd31bec1da964cb3c9cc8fc32e3388f62bc85257552ce5c8c796: Pulling from library/rabbitmq
no matching manifest for linux/amd64 in the manifest list entries
exit status 1
```

![image](https://user-images.githubusercontent.com/3391958/144584081-40b82a07-b681-41ae-9308-2419a44a1814.png)

**Comment by lanarchyste** [comment]
I have the same problem for version 3.9.11-management

**Comment by yosifkit** [comment]
![image](https://user-images.githubusercontent.com/896423/144667530-f7633485-5369-48c9-ab83-5fe09ae2efe7.png)
(https://github.com/docker-library/rabbitmq#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet)

Since there was a Debian rebuild (https://github.com/docker-library/official-images/pull/11426), the build queue is still very full and so they are still waiting to build.
