### ISSUE TITLE
Create docker-entrypoint.d

### ISSUE THREAD

**Issue by podalead** [docker-library/rabbitmq#534]
Pls, create docker-entrypoint.d for multiple script executions during newly container initialization

**Comment by tianon** [comment]
With https://github.com/docker-library/rabbitmq/pull/424 (and follow-ups), we've been heading in the _opposite_ direction, opting instead to keep the entrypoint script as simple and lightweight as possible.

In most of the database images which support some form of `docker-entrypoint-initdb.d`, there are a number of "pre-initialization" type tasks that need to be performed on a running instance of the database before starting it up for "real" use, which is why the functionality is implemented.

If there's specific initialization you need to perform on RabbitMQ before it's "ready for use", I'm sure the folks who maintain RabbitMQ would be very interested in hearing about your use case and determining whether it's something they'd want to add explicit support in RabbitMQ itself for.

**Comment by lukebakken** [comment]
@tianon agreed. @podalead please start a discussion describing your use-case here:

https://github.com/rabbitmq/rabbitmq-server/discussions

This issue should be closed.
