### ISSUE TITLE
Release 3.10.8 missing

### ISSUE THREAD

**Issue by dodgex** [docker-library/rabbitmq#577]
Hello, 

when is the Docker Release of Version 3.10.8 planned?

We are affected by memory usage issue fixed with that version and would love to get the latest release.
See https://github.com/rabbitmq/rabbitmq-server/pull/5684 and https://github.com/docker-library/rabbitmq/issues/545#issuecomment-1224977154

Thanks!

**Comment by michaelklishin** [comment]
It hasn't even been announced yet by the core team.

From the FAQ: when are [official images built after image source changes](https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what).

**Comment by tianon** [comment]
Fixed via https://github.com/docker-library/rabbitmq/pull/579 and https://github.com/docker-library/rabbitmq/commit/d28e7a1451f710c74dff43d49100c886eea362c4 -> https://github.com/docker-library/official-images/pull/13223

(This doesn't include 3.9.23 yet because I need to chase down a build failure :sweat_smile:)
