### ISSUE TITLE
CVE-2018-25032

### ISSUE THREAD

**Issue by illotum** [docker-library/rabbitmq#585]
I noticed that not all v3.9 images are on the [patched zlib](https://ubuntu.com/security/notices/USN-5355-1), e.g. reported by 

```
docker run rabbitmq:3.9.1 -- apt list
```

While a similar issues is discussed in #576, I wonder why not every v3.9 container has been updated. LMK if it should be done in this layer, I'd be happy to submit a patch.

**Comment by yosifkit** [comment]
3.9.1 was dropped in d61b9499e455ece270681c59e7e20185a900980b. So it hasn't been rebuilt since before that point. We only rebuild the current set of supported versions; i.e. the most recent release each of `3.9.x`, `3.10.x` and `3.11.x` (we follow what is shown on upstream's releases page: https://www.rabbitmq.com/versions.html).
