### ISSUE TITLE
The road to Erlang 26

### ISSUE THREAD

**Issue by michaelklishin** [docker-library/rabbitmq#636]
Hey folks @tianon @yosifkit,

Team RabbitMQ has gotten upcoming 3.12.0 and 3.11.x mostly compatible with Erlang 26. However,
no current release is compatible.

We'd like to discuss how we can make sure that this image only adopts Erlang 26 after the
patch releases of RabbitMQ that support it ship. Some members of our team believe that
older versions of this image can be "rebased" on top of Erlang 26: is this really true?

Erlang 26 provides a 5-12% throughput gain for basic workloads, so it would be great to support
it early on, but not too early :)

**Comment by michaelklishin** [comment]
I'm happy to convert this to a discussion, just figured we could use a "marker issue" for when Erlang 26 support in this image ships.

**Comment by yosifkit** [comment]
It'd be quite a lot of effort to change a past image tag to a different erlang version, but any active versions are controlled by `versions.sh`: 

https://github.com/docker-library/rabbitmq/blob/a7f33b79f2e431f4da0f6329436635512c945fab/versions.sh#L4-L10

We can just bump that when the patch version is released.  But maybe we need to adjust it so that it can auto move with a specific patch/release so that we can have the erlang bump for a pre-release version (e.g., `3.11.16` RC/beta) and not the release (`3.11.15`) as well. 🤔

**Comment by tianon** [comment]
I _think_ everything would mostly work for updating older versions (if that's really strongly desired) by creating folders and appropriate values in the right places, but I admit I haven't tested that recently to see if we've broken it.  To put that another way, very possible, not trivial, but certainly doable and not especially hard esp. since we haven't had any real major changes to the template, etc in a while.  How far back would you want to go, assuming everything works and your testing is all good?

**Comment by tianon** [comment]
(Also, issue seems pretty appropriate to me, given we're discussing concrete changes to what's maintained :bow:)

**Comment by michaelklishin** [comment]
No, we DO NOT want to upgrade older images, only starting with 3.11.16 (or even later) and 3.12.0.

But that looks good. Sounds like all we need to do is to bump the versions a few weeks after a compatible patch is released in each series.

**Comment by mkuratczyk** [comment]
Sounds good. My concern was that I've seen Erlang being bumped for existing images (eg. `3.11.0` would have Erlang 25.x.y one day but 25.a.b a few weeks later). As I understand it now, that happens only for minor/patch releases of Erlang. That's great. Thanks,

**Comment by tianon** [comment]
Yeah, for sure -- we're happy to be as proactive here as you recommend/want.  If you want us to update the Erlang major version for the pre-releases of 3.11.16 and 3.12.0, we can easily do that, but we also don't mind waiting and staying on 25 for a little bit (or a long bit, or indefinitely!) before we do the bump.  We indeed only automate the non-major version bumps. :smile:

**Comment by michaelklishin** [comment]
Someone has reminded me that those upgrading RabbitMQ and Erlang to 26 at the same time [must be on RabbitMQ 3.11.17 or later](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.12.0).

Let's hold off the move to Erlang 26 for a few months to make sure that more environments
are upgraded to `3.11.17+`.

**Comment by lukebakken** [comment]
I think that with #652 we can close this issue ... ???

**Comment by yosifkit** [comment]
Sure, feel free to ping us or make a PR when `3.12` or `3.11` should make the move to Erlang 26 as well.
