### ISSUE TITLE
Add a `rabbitmq` initialization directory similar to `mysql`/`postgre`'s `/docker-entrypoint-initdb.d`?

### ISSUE THREAD

**Issue by rsampaths16** [docker-library/rabbitmq#637]
Is it possible to support an init directory where users can mount/copy scripts to be executed on a fresh build of `rabbitmq`?
It would be really helpful for automating initialization of `rabbitmq` containers.

There seems to be an older thread related to this: https://github.com/docker-library/rabbitmq/issues/263 but it is forcing the `management_plugin` upon the users.

**Comment by lukebakken** [comment]
> It would be really helpful for automating initialization of rabbitmq containers

What sort of initialization do you need to do, *specifically?* How are you accomplishing it now?

You can always create your own entrypoint to do initialization. Please see this repository for an example:

https://github.com/lukebakken/stackoverflow-72318314-1466825

**Comment by michaelklishin** [comment]
Are there any discussions for those images that demonstrate the need for such directory? It sounds like something most people would never need, and those who do can derive their own image?

**Comment by tianon** [comment]
The use case in `mysql` and `postgres` is that without the daemon actually running, there are a lot of "database initialization" type tasks that simply cannot be performed, so that directory exists specifically to provide a way for "first time initialization" to occur on a temporary instance of the relevant daemon (listening only their relevant unix socket, not "externally" / over TCP) followed by a clean shut down and proper startup of the application.

My understanding of definitions and configuration in RabbitMQ is that they're pretty comprehensive for the types of "setup" one might need to do on a new instance, and as noted, dropping an appropriate file for one of those in the correct place is trivial (and even doing something more complex like writing a script that generates one of those is pretty trivial to add as your own derivative image's `ENTRYPOINT` that then invokes `rabbitmq` at the end).

**Comment by lukebakken** [comment]
Closing since @rsampaths16 has not followed up with our requests for more information, and the current support for definitions import should suffice.
